### ISSUE TITLE
Table examples do not render as expected

### ISSUE THREAD

**Issue by pkulikov** [MicrosoftDocs/Contribute#136]
The current look of the [Tables](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown#tables) section in the Markdown reference is as follows:
![image](https://user-images.githubusercontent.com/15279990/48313964-54452080-e5c3-11e8-83af-e2c259075051.png)

Note, the all three columns are left-aligned. 

At the same time, the [GitHub preview](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/how-to-write-use-markdown.md#tables) of that section is as expected:
![image](https://user-images.githubusercontent.com/15279990/48313998-a4bc7e00-e5c3-11e8-9081-6446dc77f78c.png)

The similar issue with alignment is in another [Markdown reference article](https://docs.microsoft.com/en-us/contribute/markdown-reference#tables). Check the last example that shows how to align column content:
![image](https://user-images.githubusercontent.com/15279990/48314039-23192000-e5c4-11e8-9073-5f263d02aef6.png)

**Comment by markgort86** [comment]
I look at this issue, it looks fixed right now. All columns are alligned correctly. The left column is rendering left, the right one is rendering to the right and the centered column in rendering in the middle. I checked this also at the Github preview, the docs page. Can you check it on you're end? Otherwise this issue can be closed.

**Comment by pkulikov** [comment]
@markgort86 indeed, the issue looks to be resolved. Closing it then. Thanks!
