### ISSUE TITLE
Is there a way to specify image size?

### ISSUE THREAD

**Issue by scooley** [MicrosoftDocs/Contribute#146]
I really want to scale an image.  Should I include white space in the image or is there a better way to set max size?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd2bb3d-3104-1be7-7232-8a194074af4b
* Version Independent ID: 2efecbe2-8538-8659-7740-6f8852f7875b
* Content: [Markdown reference for OPS and docs.microsoft.com - Contributor Guide](https://docs.microsoft.com/en-us/contribute/markdown-reference#images)
* Content Source: [Contribute/markdown-reference.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/markdown-reference.md)
* Product: **non-product-specific**
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by JasonWHowell** [comment]
Images on the docs site generally scale down images to the width of the page. Aim for around 1000 px wide. I think it renders more like 800 px on a desktop, but much less on Mobile generally. Docs markdown doesn't have size tag since the design is responsive to the device. 

Does that help? Thanks, Jason
