### ISSUE TITLE
Unable to provide feedback on some pages

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Contribute#226]
Please fix the pages in this section so that we can provide content feedback https://docs.microsoft.com/en-us/connectors/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#get-more-involved)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JasonWHowell** [comment]
@DeanGross Good feedback!

The docs teams turn on feedback control in some areas, but in other areas the feedback is intentionally turned off. For example, one case is if there is machine generated content that will be overwritten by the system (Connector References appears to be auto-generated), and another is when the product engineering team opts to use forums for Q&A instead of github issues. 

For those areas I recommend to use the forums for discussion. 
- [https://powerusers.microsoft.com/t5/Microsoft-Flow-Community/ct-p/FlowCommunity](https://powerusers.microsoft.com/t5/Microsoft-Flow-Community/ct-p/FlowCommunity)
- [https://powerusers.microsoft.com/t5/Flow-Ideas/idb-p/FlowIdeas](https://powerusers.microsoft.com/t5/Flow-Ideas/idb-p/FlowIdeas)

Copying some key contributors for the Flow Connectors in case they know the history and for awareness:
CC: @divyaswarnkar @sunaysv @MSFTMan @mgblythe 

Thanks, Jason

**Comment by DeanGross** [comment]
Thanks for the explanation. in those cases where it is turned off, would it be possible to add some links to the recommended forums?

**Comment by JasonWHowell** [comment]
@DeanGross I forwarded your request to the right folks. They don't have access to this repo, and I don't have access to theirs, so I've done all I can do for now. Feedback received. Thanks, Jason
