### ISSUE TITLE
Text formatting guidelines are inconsistent

### ISSUE THREAD

**Issue by qbit86** [MicrosoftDocs/Contribute#441]
Text formatting guidelines are inconsistent regarding file names.

How do I format file names like .gitattributes in documentation? Different guidelines and actual usages utilize all kinds of formatting:
* Italics: _.gitattributes_
* Bold: **.gitattributes**
* Code: `.gitattributes`
* No formatting: .gitattributes

[Text formatting guidelines] prescribe to [use italics](https://docs.microsoft.com/en-us/contribute/text-formatting-guidelines#examples-1), but later give [code style](https://docs.microsoft.com/en-us/contribute/text-formatting-guidelines#examples-of-fenced-code-blocks) in example. They explicitly forbid using bold later, but [Formatting text in instructions](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions) prescribes to use bold in that context. [Formatting common text elements](https://docs.microsoft.com/en-us/style-guide/text-formatting/formatting-common-text-elements) recommends applying no style.

[Text formatting guidelines]: https://docs.microsoft.com/en-us/contribute/text-formatting-guidelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b469264d-8c9b-1ce9-3b8b-67803f44501f
* Version Independent ID: 02f9dc5e-9069-da11-94a6-5a4e125ecab4
* Content: [Text formatting guidelines - Contributor Guide](https://docs.microsoft.com/en-us/contribute/text-formatting-guidelines)
* Content Source: [Contribute/text-formatting-guidelines.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/text-formatting-guidelines.md)
* Product: **non-product-specific**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for your question. We will look into making our guidance documentation more consistent. However, there is no enforcement mechanism and so there will always be variations in actual usage. 

My recommendation is to follow the guidance to use italics for file and folder names.

>Text formatting guidelines prescribe to use italics, but later give code style in example.

Code style is used in the later example because the file name is shown as a PowerShell command.

> They explicitly forbid using bold later, but Formatting text in instructions prescribes to use bold in that context. 

This is inconsistent with the italics guidance, but the bold guidance is specifically for "file names in procedures if you're directing the customer to select, type, or otherwise interact with the name."

> Formatting common text elements recommends applying no style. 

The guidance here is focused on capitalization rather than text style.

**Comment by Jim-Parker** [comment]
@qbit86  I'm closing this because it looks like we have clarification of the issue/question. Let me know if there are further questions. Thanks for providing this feedback.

**Comment by Jim-Parker** [comment]
Thanks for helping out @tdykstra
