### ISSUE TITLE
Applicable to Teams as well ?

### ISSUE THREAD

**Issue by brilwjm** [MicrosoftDocs/Contribute#514]
[It literally mentions about SFBO, technical experts like us know it's also applicable to Teams, but it's better mention it in this article. Otherwise, clients are always having concern and doubt saying it's all about SFBO, will it work for Teams ???]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/master/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @Jim-Parker
* Microsoft Alias: **jimpark**

**Comment by jehchow** [comment]
Hi @brilwjm - I've taken a look at your comment, but I'm not sure what article you were viewing when you raised this issue. GitHub is reporting that you were looking at the contributor guide overview, but unfortunately I don't see any reference to SFBO. 

If you can recall what page you were on when you submitted this issue, please comment further; otherwise I will close this in 5 business days. Apologies for any inconvenience.
