### ISSUE TITLE
Unable to find how to either edit or create issue for Edge WebView2 reference docs

### ISSUE THREAD

**Issue by alesandroortiz** [MicrosoftDocs/Contribute#607]
Unable to find how to either edit or create issue for https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1150.38

Contributor Guide points to edit button, but there's no edit button nor feedback button on page: https://docs.microsoft.com/en-us/contribute/

Would be helpful to have either an edit button or feedback button, or absent that, some other information about this in the Contributor Guide page, such as a GitHub repo for those docs or other method to submit feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs contributor guide overview - Contributor Guide](https://docs.microsoft.com/en-us/contribute/#create-quality-issues)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by alesandroortiz** [comment]
In this case, I noticed a minor typo (`it is ignore` should be `it is ignored`) and wanted to fix it or create an issue to get it fixed.

**Comment by alesandroortiz** [comment]
Prior to opening this issue, I also looked at https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute which pointed to https://github.com/dotnet/dotnet-api-docs and https://github.com/dotnet/docs but was unable to find the relevant document there. This might be more of a Microsoft Edge WebView2 doc than a .NET doc, but either way was unable to find the right place from the Contributor Guide.

**Comment by carlyrevier** [comment]
Hi @alesandroortiz - Thank you for attempting to contribute to our documentation.

Unfortunately, not all docsets accept public contributions. The contributor guide states this on the [landing page](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-documentation): "If the Edit button isn't present, it means the content isn't open to public contributions. Some pages are generated (for example, from inline documentation in code) and must be edited in the project they belong to." 

Since the documentation you're trying to edit is an API reference, my guess is that it might not be editable because it might be generated.

I visited the page you're trying to edit and then navigated up a few levels to the ["Reference" page](https://docs.microsoft.com/en-us/microsoft-edge/webview2/webview2-api-reference?view=webview2-dotnet-1.0.1150.38#feedback), which does have a feedback mechanism. I recommend posting this issue in that repo, as they'd be the best ones to help solve it.

**Comment by alesandroortiz** [comment]
Hi @carlyrevier, thanks for the info. I've filed https://github.com/MicrosoftDocs/edge-developer/issues/1807 for this typo.

For the future, will go up a few levels until I find a feedback button as you indicated. Would be helpful to include this in the landing page for the Contributor Guide since that's where I went first (from the `Contribute` link in the footer).

**Comment by carlyrevier** [comment]
Thanks for the feedback!
