### ISSUE TITLE
Tomas Rodriguez Mendez broke in my house and stole my daughter Esther's birthday certificates. 

### ISSUE THREAD

**Issue by caprice92** [MicrosoftDocs/Contribute#745]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Learn documentation contributor guide overview - Contributor guide](https://learn.microsoft.com/en-us/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute/blob/main/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @carlyrevier
* Microsoft Alias: **cahublou**

**Comment by carlyrevier** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.

Also, this post has been edited due to Code of Conduct violations.
