### ISSUE TITLE
GraphQL Syntax Highlighting - No text color variation

### ISSUE THREAD

**Issue by seantleonard** [MicrosoftDocs/Contribute#853]
Follow up to #793.

I recognize that GraphQL is in the supported languages list to be used for code blocks in docs.

What doesn't work, is syntax highlighting like other languages. My team's documentation has examples of lack of GraphQL syntax highlighting even though we add the appropriate code blocks.

https://learn.microsoft.com/en-us/azure/data-api-builder/views-and-stored-procedures#graphql-support-for-stored-procedures

Pasted a screenshot below for ease of access:
![image](https://github.com/MicrosoftDocs/Contribute/assets/6414189/ec6ecfec-d257-4c51-81aa-ce405f71f69c)

**Comment by carlyrevier** [comment]
@tdykstra - Is this something you can address?

**Comment by tdykstra** [comment]
@meganbradley Can you help with this?

**Comment by carlyrevier** [comment]
@seantleonard - If this issue is ongoing, please submit a SiteHelp request here: https://sitehelp.microsoft.com/ 

This allows us to better track and respond to the issue internally and make sure it gets to the correct product owner. Thanks!

**Comment by seantleonard** [comment]
@carlyrevier this is still an issue. I didn't see any commits being pushed here to Microsoft Learn that would have changed the experience.

The link in my original post contains multiple GraphQL code snippets which have no code syntax highlighting. That is still the case. https://learn.microsoft.com/en-us/azure/data-api-builder/views-and-stored-procedures#graphql-support-for-stored-procedures

Can we reopen this?

**Comment by seantleonard** [comment]
Added an issue to your linked portal.

**Comment by carlyrevier** [comment]
@seantleonard - Thanks for submitting a ticket. I closed this issue because it sounds like the problem is in how Learn renders GraphQL, not necessarily with the documentation itself. (If I'm wrong on that, please let me know what documentation needs to be fixed, or feel free to open a PR to fix it yourself.) Learn Platform engineers don't monitor GitHub issues, so that's why the internal ticket is important. When the issue is fixed by the Learn Platform engineers, we can update the documentation here as needed. Also, issues are being turned off for most Microsoft Learn repos throughout this year, so there's no point to reopening or creating new issues.
